<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/styles/styles.css">
    <title>Biblioteca Virtual</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

</head>
<body>
<?php
    include("body.php");
 ?>
  <p style="color:red";>Lorem ipsum dolor sit amet consectetur adipiscing elit congue enim, suscipit commodo curabitur sodales tempus condimentum dui nunc mi, aenean facilisi ornare augue nulla orci mus vulputate. Tempor cras egestas a feugiat sodales gravida proin, duis litora vulputate torquent aliquet. Magna nulla egestas lobortis turpis nisi aenean tellus eleifend sem, maecenas gravida litora curae congue nascetur volutpat. Dignissim enim pellentesque sapien praesent fermentum ad dui, gravida felis volutpat netus porta potenti ultricies, nostra duis nam cras nascetur varius. Vestibulum elementum est nunc erat torquent dictum venenatis in bibendum, hac at risus pulvinar vulputate facilisi magnis dictumst pellentesque, ultricies sem tortor class porta velit nascetur nam. Pellentesque platea est dignissim per nec suscipit faucibus nisi, ultrices rutrum elementum mi vel curae ad, dis posuere sociis egestas sagittis non aptent. Curabitur lectus tincidunt primis lobortis cum eleifend vehicula dictum himenaeos, natoque dis mattis dapibus montes massa pulvinar risus porttitor, semper praesent aptent phasellus dignissim sapien ac fusce. Sollicitudin donec dictum tortor sodales imperdiet magnis curae, taciti leo cras a aptent suscipit lacinia sagittis, et molestie potenti eros varius luctus. Lacus purus sodales pulvinar sapien eleifend nullam, tellus litora dictum vulputate ornare, sagittis diam tortor torquent lobortis.

Ultrices rutrum ut vulputate nam lacus arcu torquent purus, id congue cras bibendum ridiculus interdum rhoncus vivamus eleifend, potenti dictumst netus aenean et leo consequat. Fusce dui conubia eleifend mus ligula etiam pellentesque enim facilisi tempor taciti tincidunt posuere a vulputate rhoncus tempus sociis, eget vel quisque id libero congue habitasse euismod semper fames gravida ultricies hendrerit viverra cum senectus aliquet. Nullam primis etiam metus mus lacinia conubia cras pharetra aenean, sagittis placerat cursus curabitur fringilla suscipit sed class proin leo, erat semper nam consequat et facilisi scelerisque nibh. Odio integer volutpat nullam erat dis non magnis magna nascetur porta sociosqu proin, elementum id faucibus dictum nostra ac nibh morbi ullamcorper sociis dignissim laoreet, donec porttitor hendrerit maecenas habitasse felis litora vulputate arcu est ligula. Lectus felis eleifend nunc elementum ante semper arcu, hac maecenas sed potenti diam aliquet nisi turpis, eget aenean purus erat sodales urna. Ultrices justo eleifend penatibus habitant potenti fermentum sapien aptent, duis nam bibendum inceptos orci purus quam libero laoreet, viverra eu suspendisse pharetra facilisis eget euismod vel, ridiculus placerat mollis eros suscipit metus ac. Lectus natoque tempor cras viverra risus curae phasellus cubilia, ornare leo tempus vehicula nisi mus molestie fames, non dictum a nunc ullamcorper egestas inceptos tellus, habitant dignissim parturient duis blandit elementum suscipit. Morbi primis curae phasellus pulvinar tempus ullamcorper penatibus auctor, facilisis duis pretium ultricies urna elementum ultrices leo, litora ridiculus praesent inceptos cursus libero nascetur.

Est sociosqu commodo nostra faucibus conubia natoque morbi diam, dis pulvinar egestas eros nec lacinia sem gravida, orci cursus potenti mollis maecenas magna rutrum. Et orci imperdiet aliquet donec dignissim ante dictumst nam, class inceptos commodo bibendum molestie lectus pharetra senectus justo, phasellus natoque libero mollis curae arcu morbi. Phasellus litora malesuada mollis dictum hendrerit vivamus lectus ultrices penatibus, duis venenatis molestie volutpat potenti quis curae luctus, faucibus commodo ante feugiat tellus sodales interdum vitae. Donec malesuada nullam vulputate venenatis nunc lacinia ligula ultricies viverra, tortor class est platea nascetur torquent sapien interdum a, curabitur volutpat sed auctor magnis urna habitant ad. At pretium congue conubia maecenas vel hendrerit et tortor ornare ad, parturient proin nullam suscipit vehicula nisl phasellus a. Non fusce hac lectus vestibulum luctus duis mauris aliquet semper ad class integer vitae, volutpat magnis nisi id ullamcorper pharetra vel habitant nulla tincidunt congue. Vulputate magnis fermentum consequat euismod duis commodo ultrices, tellus netus cum sed nullam sodales, metus iaculis facilisis vestibulum blandit erat. Gravida sociis tristique molestie leo sociosqu quisque enim faucibus condimentum convallis aliquet, eros rutrum eleifend dictumst massa ac curabitur aptent eget. Pretium elementum congue sem platea netus odio metus aliquam habitant, cursus consequat facilisis tempus montes vitae sociis.

Imperdiet gravida dictum accumsan nibh nulla proin facilisis montes, suscipit inceptos senectus sociosqu congue cras nam, neque egestas odio condimentum nec vivamus blandit. Tristique non torquent elementum neque cras nostra consequat netus, vehicula laoreet sapien natoque parturient facilisis aliquam id, egestas gravida varius per et dictum nascetur. Est nunc sagittis dictumst montes ultricies porttitor gravida semper blandit sociis enim in suscipit, iaculis urna felis suspendisse litora nisi ornare pellentesque sed sapien parturient vehicula. Lacinia ut semper ad vestibulum eros erat litora nullam lectus, aliquet suspendisse nec bibendum nostra congue porttitor rutrum curae, montes vulputate cum per pellentesque neque primis nulla. Porta curabitur dictum nunc mauris gravida purus enim eu, nostra elementum nec feugiat placerat orci himenaeos risus, sociosqu senectus vivamus tristique justo habitant parturient. Parturient cursus vulputate tristique sem ac tempus curabitur himenaeos, aenean odio dis penatibus malesuada dictum natoque, imperdiet posuere elementum tellus non mattis euismod.
</p>
</body>
</html>
